### ISSUE TITLE
Bucket names too long

### ISSUE THREAD

**Issue by Sapd** [jamstack-cms/jamstack-cms#12]
I'm trying to simply test jamstack and followed the README.

While calling `yarn run jamstack-init` I got such errors:
```
CREATE_FAILED      S3Bucket
Bucket name should be between 3 and 63 characters long
CREATE_FAILED      amplify-jamstack-cms-de-161709-storagejamstackcms-F16NAOJ9V22H AWS::CloudFormation::Stack
```

I even tried using an very short environment name (only 2 characters) with no help. It seems like it simply creates too long names.

**Comment by dabit3** [comment]
I think I know the issue here, it has to do with the way `jamstack-init` works if called more than once. You can go into the file and change this to something smaller until I push up a fix, but until then if you only run `jamstack-init` once it should work fine (I think you may have run it more than once).

**Comment by dabit3** [comment]
Ok, this issue should be resolved now. Thanks for the issue!
